### ISSUE TITLE
There is no landing page when we click any of the cards

### ISSUE THREAD

**Issue by lakshay451** [TechNodes2-0/ElectiveHub#10]
![Screenshot (895)](https://github.com/TechNodes2-0/ElectiveHub/assets/89472581/57fc98fe-4fd7-46af-9f54-f339189bdafa)
we can have a landing page for each of the cards shown in the homepage.

I am willing to work on this issue.

**Comment by Nishitbaria** [comment]
You can start working on this issue @lakshay451 ✨

**Comment by lakshay451** [comment]
Any updates on this? Does it require any other changes?
@Nishitbaria
