### ISSUE TITLE
[Feat]: Adding Modal to Logout Button

### ISSUE THREAD

**Issue by VishalGaurav01** [TechNodes2-0/ElectiveHub#100]
### Is your feature request related to a problem? Please describe.

While Navigating on different pages through the navbar... click on the logout button and have to log in again.
This is a time consuming process.

### Describe the solution you'd like.

Add a modal to the logout button that will ask for confirmation of signing out. 
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/97465452/9b80973b-95a6-4b16-879e-fe023147db83)
Assignee: Please assign this issue to me. I like to contribute more to this project. 

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Yash636261** [comment]
assigning to you @VishalGaurav01, you can start working on it.
