### ISSUE TITLE
[Feat]:Adding About Us page along with Contact Us form  

### ISSUE THREAD

**Issue by VishalGaurav01** [TechNodes2-0/ElectiveHub#102]
### Is your feature request related to a problem? Please describe.

No About Us and Contact Form exist.

### Describe the solution you'd like.

Attractive UI about us page and contact form.
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/97465452/c284abb5-fc63-4e48-86ab-4ea0817efc92)
Assignee: Please Assign this issue to me...I have already completed your previous issues.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Assigning to you, just make sure it goes well with the overall design of the website

**Comment by anshkie** [comment]
@Yash636261 Can you assign this project to me?
