### ISSUE TITLE
Adding GSSoC image 

### ISSUE THREAD

**Issue by Arpcoder** [TechNodes2-0/ElectiveHub#104]
### Issue Description

Adding GSSoC image in readme would help contributors to know that this project is open for GSSoC contributions

### Checklist

- [X] I have checked the existing [issues](https://github.com/TechNodes2-0/ElectiveHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Yash636261** [comment]
Hey @Arpcoder , there is no need to add GSSOC image to readme as of now. closing this one, look for other issues.
