### ISSUE TITLE
fixing overflow issue in studentList

### ISSUE THREAD

**Issue by powerstone666** [TechNodes2-0/ElectiveHub#107]
### Description

in studentList ,students are exceeding the div and overflowing to footer

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by powerstone666** [comment]
assign this to me under gssoc

**Comment by Yash636261** [comment]
can you share the screenshot of same?
