### ISSUE TITLE
[Footer section]: footer section

### ISSUE THREAD

**Issue by dev04sa** [TechNodes2-0/ElectiveHub#109]
### Is your feature request related to a problem? Please describe.

as you can see footer section is missing in website.

### Describe the solution you'd like.

i want to create a good footer section UI , kindly assign this issue to me.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [x] I want to work on this issue. (optional)

**Comment by Manaswini123456** [comment]
I would also like to contribute and provide my insights kindly assign me with this issue.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by anshikatiwari20** [comment]
I've observed that the footer section of the project is not up to standard. 
As a participant in GSSoC'24, I've thoroughly reviewed all features and believe I can contribute effectively to improving the footer section.
Could you please assign this issue to me and add the appropriate label?

**Comment by Yash636261** [comment]
Hey @dev04sa, I can't find. which page doesn't have the footer?

kindly share mention the page so I can further decide.
