### ISSUE TITLE
redesign the user profile

### ISSUE THREAD

**Issue by Kaveyan** [TechNodes2-0/ElectiveHub#110]
### Is your feature request related to a problem? Please describe.

![Screenshot 2024-05-12 151431](https://github.com/TechNodes2-0/ElectiveHub/assets/120024889/9c6619e0-507c-4918-868e-ea39778e7265)

### Describe the solution you'd like.

improve the ui

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Kaveyan** [comment]
assign the work to me

**Comment by Yash636261** [comment]
similar issue is already there, and it is assigned to someone else. kindly look for other issues.
