### ISSUE TITLE
[Feat]:  I want to add signup and sign in with google and github  option 

### ISSUE THREAD

**Issue by AnitSarkar123** [TechNodes2-0/ElectiveHub#113]
### Is your feature request related to a problem? Please describe.

i want to add funcionallity for user to sign in with google and github

### Describe the solution you'd like.

To create login and sing up using google

### Describe alternatives you've considered.

none

### Additional context.

none

### Show us the magic with screenshots

i send with PR

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Des-pait** [comment]
Hey, I can add google authentication for signUp and signIn . Kindly allot this issue to me as GSSoC'24 contributor.

**Comment by AnitSarkar123** [comment]
Please first assign me under GSSOC'24

**Comment by Yash636261** [comment]
Hey @AnitSarkar123  , we are not planning google sign up as there is no need of it as of now. so, I'm closing this issue.
