### ISSUE TITLE
[Feat]: want to add a Contact Us from and implement the faciality to automatically sent message to the owner's email when the user is submitted the message

### ISSUE THREAD

**Issue by AnitSarkar123** [TechNodes2-0/ElectiveHub#114]
### Is your feature request related to a problem? Please describe.

to contact owner by user

### Describe the solution you'd like.

using email.js

### Describe alternatives you've considered.

none

### Additional context.

none

### Show us the magic with screenshots

i will attached it with my PR

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
