### ISSUE TITLE
Admin Dash board Elective subject app is not proper

### ISSUE THREAD

**Issue by Rohitha-pudu** [TechNodes2-0/ElectiveHub#118]
### The cards are are not proper
###Login and signup there is no password view
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/116823590/dbeaf61b-ec46-4f2c-ab58-c26988294bf8)

assign this issue to me

**Comment by Str1905** [comment]
Hey Please assign it to me. I would like to resolve it.

**Comment by Yash636261** [comment]
assigning to you @Rohitha-pudu , you can start working on it.
