### ISSUE TITLE
[Feat]: Automated Greet Workflow

### ISSUE THREAD

**Issue by sanmarg** [TechNodes2-0/ElectiveHub#124]
### Is your feature request related to a problem? Please describe.

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

### Show us the magic with screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/50082154/a9cda80c-de4e-4e6e-bf48-e447a9f7acda)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
assigning to you @sanmarg, you can start working on it.
