### ISSUE TITLE
[Feat]: Icon should be fixed , it overlaps text 

### ISSUE THREAD

**Issue by kapilG0** [TechNodes2-0/ElectiveHub#126]
### Is your feature request related to a problem? Please describe.

The icon for scroll to top overlaps text in mobile mode.

### Describe the solution you'd like.

I want to fix that issue

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by kapilG0** [comment]
I request to please assign this issue to me under gssoc 24

**Comment by kapilG0** [comment]
> can you share screenshot of the problem ?

![Screenshot_20240513_194905](https://github.com/TechNodes2-0/ElectiveHub/assets/59639410/03ab4201-700c-44ac-934c-edcb85e7ac17)
As you can see above contact text is overlapping with arrow up box

**Comment by Yash636261** [comment]
Assigning to you, don't make the scroll button fixed just move it a bit on the right side.

**Comment by kapilG0** [comment]
Hello @Yash636261  i have fixed that issue . raised pr for the same https://github.com/TechNodes2-0/ElectiveHub/pull/144. Thank you

**Comment by kapilG0** [comment]
> Hello @Yash636261 i have fixed that issue . raised pr for the same #144. Thank you

Hello @Yash636261 can you please review that pr #144 i have updated the pr request if anything pending please let me know
