### ISSUE TITLE
Auto Updated Copyright

### ISSUE THREAD

**Issue by siddhanttomar2003** [TechNodes2-0/ElectiveHub#133]
### Is your feature request related to a problem? Please describe.

Existing copyright is manual which needs to be changed every year. I can add automatic copyright which does not need any manual work every year.

Assign me this issue under GSSoC '24. I already started working on this.
<img width="922" alt="Screenshot 2024-05-13 202458" src="https://github.com/TechNodes2-0/ElectiveHub/assets/141900451/56d5f06c-6fd8-4c96-bebf-9454dc7b5da5">
### 

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by siddhanttomar2003** [comment]
I have started working on this issue @Yash636261 , could u plz assign it

**Comment by Yash636261** [comment]
Similar issue exists and already resolved. closing this one, kindly look for other issues.
