### ISSUE TITLE
Improvement on admin dashboard 

### ISSUE THREAD

**Issue by Samani-Humaira** [TechNodes2-0/ElectiveHub#135]
### Description

1. Displaying Subject Names Properly in Admin Dashboard
2. Removing a  broken link in the footer's website logo can be a frustrating user experience and can detract from the professionalism of the website.
    

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/142516438/bf41fc9d-c178-4155-948f-39b3a56fd657)

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/142516438/6cdc8a3e-c80c-4b4b-b451-1d051417dd87)

### Additional information

Hey @Nishitbaria  please assign this task to me under GSSOC'24 

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Abhinav-Sharma06** [comment]
hi @Samani-Humaira please assign me this task under gssoc 2024 and also can you give tags to this issue

**Comment by Yash636261** [comment]
assigning to you @Samani-Humaira  , you can start working on it.

**Comment by Madhuril-Bhaskar** [comment]
please assign this task to me
