### ISSUE TITLE
[Feat]: Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [TechNodes2-0/ElectiveHub#137]
## Security Feature
In your application anyone can enter using **temporary or disposable email**.

### Describe the solution you'd like.

I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

### Additional context.

Assign me this work under GSSoC24, I will implement it.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
