### ISSUE TITLE
contributor section 

### ISSUE THREAD

**Issue by Anamika-Ratna** [TechNodes2-0/ElectiveHub#139]
### Is your feature request related to a problem? Please describe.

Why to miss out on the people who have worked on this project ?! Lets add a contributor section.

### Describe the solution you'd like.

Adding a contributor section to display the profiles of the contributors.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
We are not looking for this right now. closing this right now, will let you know if we need one in future.

Thanks. : )
