### ISSUE TITLE
Outdated Twitter Logo in Follow Us Section

### ISSUE THREAD

**Issue by kvdevlopment** [TechNodes2-0/ElectiveHub#141]
### Description

The Follow Us section on the ElectiveHub website currently displays an outdated version of the Twitter logo. Despite efforts to maintain consistency and professionalism across the site's branding elements, the Twitter logo remains outdated, which may create an impression of neglect or outdated information. We attempted to review and update all branding elements to align with current standards, but the outdated Twitter logo persists. It's crucial to rectify this issue promptly to ensure the website's visual consistency and credibility.

### Screenshots

**You can see below the outdated twitter logo**

![2024-05-14 02_54_18-](https://github.com/TechNodes2-0/ElectiveHub/assets/109462746/9cb6cbbc-e169-4734-b15d-204cb626066a)

### Additional information

The outdated Twitter logo may impact the website's overall aesthetic appeal and user perception.
Consistency in branding elements, including social media logos, is essential for maintaining professionalism and trustworthiness.
Updating the Twitter logo to the latest version will ensure alignment with current branding guidelines and industry standards.
This issue may also extend to other social media logos present on the website, emphasizing the importance of a thorough review and update of all branding elements.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by kvdevlopment** [comment]
Assign me the issue under the label GSSoC24 so that I can start working on it.

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
