### ISSUE TITLE
Bug: Active button is static 

### ISSUE THREAD

**Issue by sahiljarngal** [TechNodes2-0/ElectiveHub#142]
### Description

The active button doesn't change while changing the routing of the page.(like open signUp page, etc)

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/97387822/bb301a3a-6448-42ea-aa2f-64d1501a04ac)

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
