### ISSUE TITLE
After click on icons nothing happens, Cursor style must be pointer while hovering social icons

### ISSUE THREAD

**Issue by kapilG0** [TechNodes2-0/ElectiveHub#145]
### Description

I am trying to click on follow us icons but nothing happens 

### Screenshots

![issue](https://github.com/TechNodes2-0/ElectiveHub/assets/59639410/83df9cd3-0079-4b08-a9d5-2ab65812f570)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by kapilG0** [comment]
Hello @Yash636261 Can you please assign this issue to me under gssoc . If the social urls is ready then I can integrate those in this links

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
