### ISSUE TITLE
[Feat]: In the mobile view, some styles of the navbar need to be changed.

### ISSUE THREAD

**Issue by safal45** [TechNodes2-0/ElectiveHub#146]
### Is your feature request related to a problem? Please describe.

In the mobile view, some styles of the navbar need to be updated. These changes will improve the navigation experience on smaller screens.
![Screenshot 2024-05-14 at 11-27-25 ElectiveHub](https://github.com/TechNodes2-0/ElectiveHub/assets/130926002/a6a8eac4-a318-42a3-8c33-57d9f09bb916)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
what is your solution for this issue? and always put screenshots only in screenshot section.

**Comment by Yash636261** [comment]
Okay, assign it to you.
