### ISSUE TITLE
adding hovering effect to icons

### ISSUE THREAD

**Issue by reshamsai150** [TechNodes2-0/ElectiveHub#149]
### Is your feature request related to a problem? Please describe.

![Screenshot 2024-05-14 132513](https://github.com/TechNodes2-0/ElectiveHub/assets/164533685/af4c910a-8c11-4b8b-9cb1-2481e4406232)
I want to add a hovering effect to these icons and make them attractive assign this issue 
to me
### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
