### ISSUE TITLE
Improve the Design of Newsletter ✨ 

### ISSUE THREAD

**Issue by Nishitbaria** [TechNodes2-0/ElectiveHub#15]
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/85815172/a01e976a-4eed-4bc0-ada1-c52091e21565)

Text is collapse with each other fix it and also improve the styling

**Comment by adityakhattri21** [comment]
Can You assign this to me ..

**Comment by Nishitbaria** [comment]
you can start working on this issue @adityakhattri21  ✨

**Comment by adityakhattri21** [comment]
Can you add SLOP tag in this Issue

**Comment by Nishitbaria** [comment]
any updates @adityakhattri21

**Comment by adityakhattri21** [comment]
@Nishitbaria I have made some changes .... wanted your opinion on them before final commit
