### ISSUE TITLE
overlapping of button in admin Dashboard

### ISSUE THREAD

**Issue by AMISH-KHAN** [TechNodes2-0/ElectiveHub#153]
### Description

In admin dashboard inside Subject, there are 4 subjects which has 3 buttons which are overlapping .

### Screenshots

![Screenshot 2024-05-14 174357](https://github.com/TechNodes2-0/ElectiveHub/assets/123164129/daf04a26-5017-49d6-b1d4-6505c961878d)

### Additional information

Please assign this issue to me under Gssoc

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
