### ISSUE TITLE
[Feat]: Adding toast instead of alert

### ISSUE THREAD

**Issue by AMISH-KHAN** [TechNodes2-0/ElectiveHub#154]
### Is your feature request related to a problem? Please describe.

When we login with incorrect credential an undefined alert comes which not only blocks the website but can also confuse the user due to the lack of information.

we can add toast which can tell user that either the user does not exits or password or email is incorrect.

### Describe the solution you'd like.

we can add toast which can tell user that either the user does not exits or password or email is incorrect.

### Additional context.

Please assign this issue to me under GSSoc and add necessary labels

### Show us the magic with screenshots

![Screenshot 2024-05-14 175806](https://github.com/TechNodes2-0/ElectiveHub/assets/123164129/c184b49c-2210-4178-8c31-c3b68d27528f)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
