### ISSUE TITLE
[Feat]: Proper Authentication system

### ISSUE THREAD

**Issue by r7projects-shayan** [TechNodes2-0/ElectiveHub#158]
### Is your feature request related to a problem? Please describe.

Currently there is no proper authentication system. Anyone can come with any email and login if they use an 

@gmail.com after their email. No otp verification is there.  No option to login with Google Gmail account and other 

major providers like Microsoft account, etc.

### Describe the solution you'd like.

A secure and proper authentication and login validation system for the entire page which will include Google, Facebook, 

LinkedIn, Apple, Microsoft account login, along with secure data storage system and otp (one time password) 

verification when mobile number is provided. 

This authentication system will have the powerful SOC 2 type 2 certified and CCPA compliant security

### Describe alternatives you've considered.

A proper validation system along with Google, Facebook, LinkedIn, Apple, Microsoft login feature and user information 

storage in a secure vault. 

### Show us the magic with screenshots

![Screenshot 2024-05-14 214319](https://github.com/TechNodes2-0/ElectiveHub/assets/167475552/5bf25a70-04d4-4198-a84e-dbc23163e68c)
![Screenshot 2024-05-14 214330](https://github.com/TechNodes2-0/ElectiveHub/assets/167475552/4fcef469-4df8-49e8-85a8-dc2c664a38df)
![Screenshot 2024-05-14 214424](https://github.com/TechNodes2-0/ElectiveHub/assets/167475552/963fb31f-bef8-4d87-805b-465d22fb02ef)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by r7projects-shayan** [comment]
@Nishitbaria kindly assign me this major issue. I will start working on it and deliver exceptional results

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
