### ISSUE TITLE
Fixing footer 

### ISSUE THREAD

**Issue by Anjali-Kedia** [TechNodes2-0/ElectiveHub#16]
<img width="1426" alt="image" src="https://github.com/TechNodes2-0/ElectiveHub/assets/91176852/64855349-910a-4edc-a9c7-4e0f4456df3b">
The footer is not fixed to the bottom of the page for the subject and student tabs in https://electivehub.onrender.com/Admin. I would like to work on fixing this.

**Comment by Anjali-Kedia** [comment]
@Nishitbaria could you please provide me details for the MONGO_URL PORT TOKEN_KEY to be added for the .env for server side, so that I can access the admin portal by signing up

**Comment by Sunny-unik** [comment]
@Yash636261 showing the DB URL isn't good. By sharing Mongodb URI publically anyone not only reads the data but also has access to modify data.
If someone wants to work locally then they have to use their own database. And for help, you can provide some dummy databases so they can work.

**Comment by SharmaDhruv2511** [comment]
I want to work on this issue. Can you please assign it to me? @Anjali-Kedia

**Comment by Nishitbaria** [comment]
you can start working on this issue ✨

**Comment by SharmaDhruv2511** [comment]
Hi, I am not able to sign-in in the app. Is it issue or there is any problem?  I have connected the database also but still not able to sing in or create account.

**Comment by SharmaDhruv2511** [comment]
How can i reproduce this scenario? @Anjali-Kedia

**Comment by SharmaDhruv2511** [comment]
Hi I am not able to login as well as sign up myself to get access to the services. Can maintainers please help me to solve the issue? @Nishitbaria  @Yash636261

**Comment by VishalGaurav01** [comment]
The footer overlaps over other components in the Admin dashboard...can fix this issue.
![Screenshot 2024-05-09 172401](https://github.com/TechNodes2-0/ElectiveHub/assets/97465452/ee252197-47b5-4f7a-a8b4-d351f190207c)
Assignee: Please assign this issue to me.
