### ISSUE TITLE
[BUG]:  Delete message not visible

### ISSUE THREAD

**Issue by aryansharma220** [TechNodes2-0/ElectiveHub#161]
### Description

The Delete message is not visible properly. Its text color should be changed.

Please assign it to me under gssoc 24

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/133234867/f8fd29ed-033e-418c-8293-fc4d6317b770)

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
assigning to you @aryansharma220, you can start working on it.
