### ISSUE TITLE
Footer section logo button bug

### ISSUE THREAD

**Issue by kushalkumar1362** [TechNodes2-0/ElectiveHub#165]
### Description

**Issue**: Clicking on "ElectiveHub" in the footer results in an error.

**Expected**: Clicking on "ElectiveHub" should redirect the user to the homepage of the website.

### Screenshots

![Screenshot_20240515-073622](https://github.com/TechNodes2-0/ElectiveHub/assets/140513098/0b486356-1ad4-4321-94e8-801257142e9e)
![Screenshot_20240515-073619~2](https://github.com/TechNodes2-0/ElectiveHub/assets/140513098/56384f56-bb67-497e-80a0-26bc89d7fcf3)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by manpreet244** [comment]
I can resolve this issue . please assign it to me under GSSOC

**Comment by manpreet244** [comment]
Assign this issue to me please

**Comment by kushalkumar1362** [comment]
@Yash636261

**Comment by Yash636261** [comment]
> @Yash636261

Hey @kushalkumar1362, this issue was already opened by someone and fixed right now.
