### ISSUE TITLE
More stylish scrollbar

### ISSUE THREAD

**Issue by uraj1** [TechNodes2-0/ElectiveHub#167]
### Is your feature request related to a problem? Please describe.

The current scroll bar is set to default

### Describe the solution you'd like.

I can change the style of scroll bar which will compliment the theme of the website

### Show us the magic with screenshots

![Screenshot (9)](https://github.com/TechNodes2-0/ElectiveHub/assets/139366493/9b67256f-f03f-4558-925d-ea19aff5f5a2)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Can you share the reference of the scroll bar you want to implement.

**Comment by uraj1** [comment]
I can make it according to the theme of the website, here are some of the screenshots for your reference.
![Screenshot (10)](https://github.com/TechNodes2-0/ElectiveHub/assets/139366493/7b23fe71-9212-4478-a8ed-8b01e0f35c58)
![Screenshot (11)](https://github.com/TechNodes2-0/ElectiveHub/assets/139366493/30705997-4852-4e01-8b74-a8b8966b5499)

**Comment by Yash636261** [comment]
assigning to you @uraj1 , you can start working on it.

choose that second one.
