### ISSUE TITLE
Stats theme is not matching with the home page theme.

### ISSUE THREAD

**Issue by VishalGaurav01** [TechNodes2-0/ElectiveHub#170]
### Description

Can fix the Stats theme with dark mode and use duo-gradient to enhance UI.

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/97465452/3e0f01f5-fa9e-42c1-bdc5-9d0d07a999c0)
Assignee: Please assign this issue to me.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
please pull the updated code to your local. That one is old. Although someone messed up it already so assigning this to you.

This is current one
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/98970491/9890cbb1-fe60-4b82-9218-0491492d6eaa)

Make sure that it should go with current theme of the webpage.

**Comment by VishalGaurav01** [comment]
which one should I change:
1.
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/97465452/9b8365fa-a2d9-4e04-a1d7-da505c8423fe)
or 2.
![Screenshot 2024-05-16 124109](https://github.com/TechNodes2-0/ElectiveHub/assets/97465452/9aff8ec6-5266-400d-8e18-c955a049e0b6)
the difference is just in the amount of white bg

**Comment by Manaswini123456** [comment]
@Yash636261 Please assign me with this task.

**Comment by Yash636261** [comment]
> which one should I change: 1. ![image](https://private-user-images.githubusercontent.com/97465452/331085182-9b8365fa-a2d9-4e04-a1d7-da505c8423fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTIyNzIsIm5iZiI6MTcxNTk1MTk3MiwicGF0aCI6Ii85NzQ2NTQ1Mi8zMzEwODUxODItOWI4MzY1ZmEtYTJkOS00ZTA0LWExZDctZGE1MDVjODQyM2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEzMTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YjNjZTMxZDAwNWE0OGQ0YTEzMDM4NzZiMjUwMTc4ZGE4ZmU5NDgxNzM5NmQzNDE3YWNiMjE5N2M2NTgyM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aCS_-wBo0yoa5ztUpSYjnMZChgbkcwo18pErtZp9Wko) or 2. ![Screenshot 2024-05-16 124109](https://private-user-images.githubusercontent.com/97465452/331085324-9aff8ec6-5266-400d-8e18-c955a049e0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTIyNzIsIm5iZiI6MTcxNTk1MTk3MiwicGF0aCI6Ii85NzQ2NTQ1Mi8zMzEwODUzMjQtOWFmZjhlYzYtNTI2Ni00MDBkLThlMTgtYzk1NWEwNDllMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEzMTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNmUxODVhMmI4NzdmNmVjMDAwYTkwZDdkODEwNTRjZDk5NjJlMWFkNWI3YmEyNjZkZDQyZmFjMjFjZTEyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Crj-eyhcoXjOmJQthHJQbumCW7oFDiuBVs4hSM2Bo5I) the difference is just in the amount of white bg

first one looks good to me, go for it.
