### ISSUE TITLE
Bug: The Electichoice Ai copilot chat bot window is not showing properly

### ISSUE THREAD

**Issue by mukulpythondev** [TechNodes2-0/ElectiveHub#171]
### Description

When cllicking on the icon the chat bot then the modal/ window opens of Elecichoice chat bot is not showing properly on screen. 

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/134795697/5576f11f-a2fa-43cc-bdda-4f8d9cb0076c)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
