### ISSUE TITLE
Text alignment of "Explore Our Awesome Features"

### ISSUE THREAD

**Issue by Ridhima10** [TechNodes2-0/ElectiveHub#177]
### Description

Text alignment of "Explore Our Awesome Features" is on the left side which is not looking good according to the layout of the website

### Screenshots

![Screenshot 2024-05-16 164319](https://github.com/TechNodes2-0/ElectiveHub/assets/85826117/d7ce0c12-8c61-44d2-ab87-c1c1af65ebec)

### Additional information

I will align it in center and since all the headings of your website are in bold, so i will make it bold which will match your theme and layout to enhance the UI

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by nishant0708** [comment]
hey i can fix this bug . please assign me under gssoc2024

**Comment by Yash636261** [comment]
assigning to you @Ridhima10, you can start working on it.
