### ISSUE TITLE
Improvement in cards

### ISSUE THREAD

**Issue by Samani-Humaira** [TechNodes2-0/ElectiveHub#178]
### Description

The card looks very displeasing, and when a user adds a subject with a lengthy description, it gives an unpleasant appearance. To improve the UI, we can limit the number of lines displayed for each description on the card, ensuring a more visually appealing layout.

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/142516438/515966ac-75f7-4901-ad18-4f3581c8d57e)

### Additional information

Hey @techking007 please assign this task to me under GSSOC'24

### What browser are you seeing the problem on?

chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Hey @Samani-Humaira, Similar issue exists and already assigned. closing this one, kindly look for other issues.
