### ISSUE TITLE
Chatbot Alignment is not proper

### ISSUE THREAD

**Issue by karishmaaa101** [TechNodes2-0/ElectiveHub#179]
### Description

On clicking the chatbot there is **no greeting,no further assistance on how to proceed further**.Along with that,the chatbot goes **off the page ,till the navbar and hides it.**
Once you **open you cannot close the chatbot too.** 

I am GSSOC'24 contributor.

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/104766763/620bf140-3823-4086-b120-6ec25881b6ce)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Hey @karishmaaa101, Similar issue exists and already assigned. closing this one, kindly look for other issues.
