### ISSUE TITLE
The Image at landing page is not responsive at screen size 1024px.

### ISSUE THREAD

**Issue by SnehansuBehera** [TechNodes2-0/ElectiveHub#180]
### Description

The Image at landing page is overflowing outside the container at screen size 1024px creating the horizontal scrollbar.

### Screenshots

![Screenshot 2024-05-16 221605](https://github.com/TechNodes2-0/ElectiveHub/assets/121883802/d868c4d3-b917-4f3c-ad98-7d567e31a97f)

### What browser are you seeing the problem on?

Firefox, Chrome, Safari

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
assigning to you @SnehansuBehera, you can start working on it.
