### ISSUE TITLE
The image at login page is not responsive.

### ISSUE THREAD

**Issue by S2103aumya** [TechNodes2-0/ElectiveHub#181]
### Description

Make the image responsive by setting their position and try to make image to be placed prior to login.

### Screenshot
![Screenshot (67)](https://github.com/TechNodes2-0/ElectiveHub/assets/132819769/30a2b944-2705-4a8b-abde-b78cdefc9b66)

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue. (optional)

**Comment by nishant0708** [comment]
hey i can fix this bug

**Comment by Yash636261** [comment]
Hey @S2103aumya, which image are you talking about?
