### ISSUE TITLE
[Feat]:  Justification of text

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [TechNodes2-0/ElectiveHub#182]
### Is your feature request related to a problem? Please describe.

Justify the text either from both the sides or at center will increase the quality of the website .

### Describe the solution you'd like.

I want that the text should be center justified in the mobile view and justified from both the ends for large displays .

### Show us the magic with screenshots

![Screenshot 2024-05-17 123729](https://github.com/TechNodes2-0/ElectiveHub/assets/118350936/974890c9-9f2a-488a-a7a8-fa6ff8b825c5)
![Screenshot 2024-05-17 123720](https://github.com/TechNodes2-0/ElectiveHub/assets/118350936/cf43cd29-a5a7-4fe0-9615-be58d8b9b2e1)
![Screenshot 2024-05-17 123707](https://github.com/TechNodes2-0/ElectiveHub/assets/118350936/af418ef2-2519-47e9-ad89-bf00f83a9765)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by JayeshYadav99** [comment]
@Ayushmaanagarwal1211  I have assigned issue to you

**Comment by Ayushmaanagarwal1211** [comment]
I will send PR today
