### ISSUE TITLE
[Feat]: Making privacy policy page

### ISSUE THREAD

**Issue by traptijindal** [TechNodes2-0/ElectiveHub#189]
### Is your feature request related to a problem? Please describe.

Hey! Please assign me this task under GSoc24.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.

**Comment by traptijindal** [comment]
Ok..
