### ISSUE TITLE
[Feat]: Add google login

### ISSUE THREAD

**Issue by rohansen856** [TechNodes2-0/ElectiveHub#197]
### Is your feature request related to a problem? Please describe.

Currently users can login using email and password only. Adding google login to the site would greatly improve the user experience.

### Describe the solution you'd like.

I would like to add a simple google login in the site.
Please assign me this issue under GSSOC'24

### Show us the magic with screenshots

![Screenshot 2024-05-18 230158](https://github.com/TechNodes2-0/ElectiveHub/assets/108976786/3e0afb00-9690-4e6b-a880-64aabb76d230)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
