### ISSUE TITLE
chat-bot issue

### ISSUE THREAD

**Issue by Parimalasri13** [TechNodes2-0/ElectiveHub#199]
### Description

when I open and chat with chatbot there is  option to close but not visible and chatbot block is not static user can able to move it all directions 

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Parimalasri13** [comment]
@sanmarg can you please assign this to me

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
