### ISSUE TITLE
Fixing Login Component

### ISSUE THREAD

**Issue by adityakhattri21** [TechNodes2-0/ElectiveHub#20]
The Login Component Says : Already Have an Account . <br>Instead It should say : New to our platform.<br> 
![Screenshot 2023-10-18 232710](https://github.com/TechNodes2-0/ElectiveHub/assets/101019545/1a9a49de-a2da-4bc6-8045-0fdc9b47e065)

**Comment by Nishitbaria** [comment]
you can start working on this issue @adityakhattri21 ✨

**Comment by gkprasanth** [comment]
@Nishitbaria Is this issue still open? I would like contribute as a part of SLOP and Hacktoberfest.
