### ISSUE TITLE
[Feat]: contact page improvement

### ISSUE THREAD

**Issue by harinisayani** [TechNodes2-0/ElectiveHub#205]
### Is your feature request related to a problem? Please describe.

I want to improve contact page to look more attractive.

### Describe the solution you'd like.

I will add icons and CSS effects to make it more attractive.

### Additional context.

I am GSSOC'24 contributor.
Please assign me this issue.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
I don't see if there is anything you can improve. can you specify it.
