### ISSUE TITLE
[Feat]: Enhancing signup page

### ISSUE THREAD

**Issue by harikasayani** [TechNodes2-0/ElectiveHub#206]
### Is your feature request related to a problem? Please describe.

I want to enhance the signup page to look beautiful.
I want to work on this issue.
Please assign me this issue.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
@harikasayani, working on two issues is not possible at same time. merging this with your login page issue.
