### ISSUE TITLE
[Feat]: Enhancing login and signUp page

### ISSUE THREAD

**Issue by harikasayani** [TechNodes2-0/ElectiveHub#207]
### Is your feature request related to a problem? Please describe.

I want to enhance the login page to look beautiful.
Please assign me this issue.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Adiaparmar** [comment]
Can you assign this issue to me for gssoc

**Comment by Yash636261** [comment]
Hey @harikasayani, can you share the design you would like to implement?

**Comment by rajshivam0432** [comment]
can you assign this task to me @harikasayani please
