### ISSUE TITLE
Unnecessary space

### ISSUE THREAD

**Issue by sharmi4590** [TechNodes2-0/ElectiveHub#208]
### Description

There's unnecessary space in the webpage which increases the webpage scrolling for the user. I will make sure to remove it.

### Screenshots

![Screenshot_20240520-231723](https://github.com/TechNodes2-0/ElectiveHub/assets/102676949/12fad857-8cb7-4ad4-91f1-ed1b363b4d5c)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Can you please pull latest code. I can't see such issue.
