### ISSUE TITLE
Subscribe Button Size and Alignment.

### ISSUE THREAD

**Issue by nileshsn** [TechNodes2-0/ElectiveHub#210]
### Description

I think the subscribe button is too big.

### Screenshots

![Screenshot (229)](https://github.com/TechNodes2-0/ElectiveHub/assets/87946769/06d0f31c-6b5f-415a-b425-74042fc54fd6)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by nileshsn** [comment]
Assign me the issue

**Comment by Yash636261** [comment]
assigning to you @nileshsn, you can start working on it.

**Comment by HimangshuRanjan** [comment]
@Yash636261, I would like to fix this issue. Please do assign me this under GSSOC'24

**Comment by nileshsn** [comment]
@Yash636261 Successfully fixed the subscribe button. PR #249
<img width="644" alt="Screenshot 2024-05-28 223946" src="https://github.com/TechNodes2-0/ElectiveHub/assets/87946769/e7505c7b-bf63-42d3-8c4d-df062e3f5f6e">
