### ISSUE TITLE
Resizing the button and hover effect on the git hub logo

### ISSUE THREAD

**Issue by YadlaMani** [TechNodes2-0/ElectiveHub#213]
### Description

The button is out of size will fix that and willl add hover effect over the git logo

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/133841094/a8b1df74-f0a3-4ef4-8347-f6a0692a2cd5)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
