### ISSUE TITLE
[Feat]: Add current year inside the footer section

### ISSUE THREAD

**Issue by ANI2707** [TechNodes2-0/ElectiveHub#215]
### Is your feature request related to a problem? Please describe.

I have permanent solution for this feature request

### Show us the magic with screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/108017771/12d53927-1fc7-4f63-9ccc-805589098c01)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by ANI2707** [comment]
@Yash636261 Please assign this issue to me under GSSOC'24

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.

**Comment by ANI2707** [comment]
ok
