### ISSUE TITLE
 Implement "Forgot Password" Feature for ElectiveHub Project

### ISSUE THREAD

**Issue by skshrinaya** [TechNodes2-0/ElectiveHub#216]
### Is your feature request related to a problem? Please describe.

Yes, the absence of a "Forgot Password" feature is a significant issue for users who may forget their login credentials. Without a way to reset their password, users are unable to access their accounts, leading to frustration and potentially causing them to abandon the platform. This lack of functionality negatively impacts user experience and can result in decreased user retention and engagement. Implementing a "Forgot Password" feature will address this problem by providing users with a reliable method to regain access to their accounts, thereby improving overall user satisfaction and trust in the platform.

### Describe the solution you'd like.

Add a "Forgot Password" feature allowing users to reset their passwords. Implement a form where users enter their email address to receive a password reset link. Generate a unique token for the link, allowing access to a secure page to set a new password. Update the password in the database and send a confirmation email upon successful reset. Ensure secure token handling and error messaging for invalid or expired tokens.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by skshrinaya** [comment]
I am very eager to work on this issue. Please assign it to me.

**Comment by Yash636261** [comment]
Issue is already there and assigned.
