### ISSUE TITLE
[Feat]: Making everything of same size and all button on the same height

### ISSUE THREAD

**Issue by YadlaMani** [TechNodes2-0/ElectiveHub#217]
### Is your feature request related to a problem? Please describe.

Now when we visit the subject page all the div's are of different lengths and the buttons are placed randomly i would like to allign all the button of the divs on the same height to make website look better
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/133841094/02c68f9e-3851-4cd4-ab3f-c086bfb89619)

### Show us the magic with screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/133841094/0752f174-0466-410a-8539-957f5b8031d3)
i can do this by giving the flex styling for all the divs 

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
assigning to you @YadlaMani, you can start working on it.
