### ISSUE TITLE
Design Privacy Policy and Licensing Page

### ISSUE THREAD

**Issue by Hemashree21** [TechNodes2-0/ElectiveHub#219]
### Is your feature request related to a problem? Please describe.

In the footer, there is a link for Privacy Policy and Licensing, I want to work on designing these 2 pages. I will make sure that the page is responsive.
@Yash636261 can you please assign this to me?

### Show us the magic with screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/138188163/9ef112f0-fa63-4e04-976f-e1d49ee720c1)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Similar issue exists and already assigned. closing this one, kindly look for other issues.
