### ISSUE TITLE
[Feat]: Proper About Us Page fully responsive

### ISSUE THREAD

**Issue by r7projects-shayan** [TechNodes2-0/ElectiveHub#220]
### Is your feature request related to a problem? Please describe.

Currently the About Us page is not of proper structure and the contact form is pasted there too. This can cause the user to have confusions while using the website. 

![Screenshot 2024-05-24 024840](https://github.com/TechNodes2-0/ElectiveHub/assets/167475552/def21f32-d13d-4062-81d7-b430887f99a1)

![Screenshot 2024-05-24 024847](https://github.com/TechNodes2-0/ElectiveHub/assets/167475552/6621ef0a-5c5b-4c2f-8a04-b61afc9b76e6)

### Describe the solution you'd like.

Proper and separate About Us page that is fully responsive. 

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by r7projects-shayan** [comment]
@Nishitbaria Kindly assign me this issue, I will start working on it

**Comment by Yash636261** [comment]
issue is assigned and already resolved.
