### ISSUE TITLE
[Feat]:  Auto Commenting feature for PR Merged 

### ISSUE THREAD

**Issue by Ratangulati** [TechNodes2-0/ElectiveHub#224]
### Is your feature request related to a problem? Please describe.

This feature aims to address the issue of inconsistent and delayed communication that occurs after merging pull requests. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. Additionally, it reduces the administrative burden on maintainers, allowing them to concentrate more on code reviews and other critical tasks.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Not required right now.
