### ISSUE TITLE
[Feat]: Auto commenting on closing an issue

### ISSUE THREAD

**Issue by Ratangulati** [TechNodes2-0/ElectiveHub#228]
### Is your feature request related to a problem? Please describe.

This feature is designed to address the issue of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and thanked for their efforts. This helps to maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Not required now.
