### ISSUE TITLE
Light/Dark toggle mode

### ISSUE THREAD

**Issue by harikasayani** [TechNodes2-0/ElectiveHub#233]
### Is your feature request related to a problem? Please describe.

I observed that there is no Light/Dark toggle mode in web page.

### Describe the solution you'd like.

I want to add Light/Dark toggle mode in web page using HTML, CSS, JavaScript.

### Additional context.

I am GSSOC'24 Contributor.
I want to work on this issue.
Please assign me this issue.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
issue already exists.
