### ISSUE TITLE
[Feat]: Adding icons to navbar 

### ISSUE THREAD

**Issue by harinisayani** [TechNodes2-0/ElectiveHub#238]
### Is your feature request related to a problem? Please describe.

I have observed that their is no icons to anchor links in navbar.

### Describe the solution you'd like.

I want to add icons to it to look more attractive.

### Additional context.

I am GSSOC'24 Contributor
I want to work on this issue.
Please assign me this task.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
issue exists.
