### ISSUE TITLE
Bug/ Updating the year at footer section

### ISSUE THREAD

**Issue by balimpuramvikasgoud** [TechNodes2-0/ElectiveHub#246]
### Description

In footer section year was mentioned as 2023 but actually it should be 2024 

Step to reproduce the bug:
1.Go to link:"https://electivehub.onrender.com/".
2.Scroll down to footer section
3.See the bug

![Screenshot 2024-05-27 202013](https://github.com/TechNodes2-0/ElectiveHub/assets/152055427/4f1caae7-ed7f-400b-b657-4a7174f68ef8)
----->Issue raised as  a Gsoc Contributor(2024)
 

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [x] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Already resolved.
