### ISSUE TITLE
Admin excess to everyone

### ISSUE THREAD

**Issue by karanop001018** [TechNodes2-0/ElectiveHub#252]
### Description

Description: The user, who is not an administrator, is able to access other users’ account details. This is a critical security issue as it breaches privacy and confidentiality norms.

Steps to Reproduce:
Log in to the system as a non-admin user.
Attempt to access account details of another user.
Expected Result: The non-admin user should not be able to access other users’ account details. An error message should be displayed, or the user should be redirected to their own account page.

Actual Result: The non-admin user is able to access other users’ account details.

Additional Notes: This issue needs immediate attention as it is a severe breach of privacy and can lead to misuse of sensitive information.

### Screenshots

![Screenshot_29-5-2024_173616_electivehub onrender com](https://github.com/TechNodes2-0/ElectiveHub/assets/96780293/2beb6358-32ae-48a7-9320-bfaf69e82fa6)
![Screenshot_29-5-2024_173533_electivehub onrender com](https://github.com/TechNodes2-0/ElectiveHub/assets/96780293/6b04a632-cf9b-41e5-98de-41ebbe36a5c8)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [x] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
issue is already there.
