### ISSUE TITLE
(GSSoC'24) Fixing Stats section

### ISSUE THREAD

**Issue by Apurv7777** [TechNodes2-0/ElectiveHub#255]
### Description

In stats sections , the titles and some texts above it are not visible. 

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/65327303/1dc16f2b-4df8-4093-b4e4-0ca7d65add13)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
are you sure you are on latest version. as i can see that section.

**Comment by Apurv7777** [comment]
Yes, I can't see still.
I am seeing it in Chrome browser, you might check in chrome, I guess.

**Comment by Yash636261** [comment]
> Yes, I can't see still. I am seeing it in Chrome browser, you might check in chrome, I guess.

I'm working on edge but checked chrome as well it's working perfectly.

**Comment by Apurv7777** [comment]
Can you share the screenshot,  just wanted to know if only in my browser it is not visible or what ?

**Comment by Apurv7777** [comment]
Can you share the screenshot,  just wanted to know if only in my browser it is not visible or what ?

**Comment by Yash636261** [comment]
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/98970491/7d2802e8-ca94-4178-acd0-060b9b80dc83)
