### ISSUE TITLE
Change copyright year 2023 to 2024

### ISSUE THREAD

**Issue by niteshbca** [TechNodes2-0/ElectiveHub#259]
### Description

Change copyright year 2023 to 2024

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/138958926/eadacfab-afb9-4d2c-8a02-9c20a38c0677)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by niteshbca** [comment]
@Yash636261 Please assign to me issue under GSSOC’24.
I can fix this issue.
Thank You !

**Comment by Yash636261** [comment]
already resolved
