### ISSUE TITLE
[Feat]: Add privacy policy page

### ISSUE THREAD

**Issue by AkhilaSunesh** [TechNodes2-0/ElectiveHub#268]
### Is your feature request related to a problem? Please describe.

 Add privacy policy page with required clauses which are not hard to understand for the users.
With proper formatting and updated looks.

### Describe the solution you'd like.

Add privacy policy

### Additional context.

Kindly assign this issue to me.

### Show us the magic with screenshots
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/140897461/b43c9e89-a7e0-45fd-b961-323b7f8d5416)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
issue is already resolved.
