### ISSUE TITLE
Feature : Adding test cases in backend

### ISSUE THREAD

**Issue by yube01** [TechNodes2-0/ElectiveHub#27]
### Is your feature request related to a problem? Please describe.

Adding test cases 

### Describe the solution you'd like.

Test cases in backend code for simple server connection

### Describe alternatives you've considered.

Using testing framework such as jest and supertest

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Nishitbaria** [comment]
Hey @yube01 can you explain to me which type of test cases you are going to add???

**Comment by Nishitbaria** [comment]
Hey @yube01  can you explain to me which type of test cases you are going to add?? ?

**Comment by yube01** [comment]
I will write simple test cases like
if server is running properly or not 
testing different kinds of route and their response
and so on
