### ISSUE TITLE
footer link is dummy

### ISSUE THREAD

**Issue by Varsani2520** [TechNodes2-0/ElectiveHub#275]
### Description

footer link is not redirect the specific their page all the content redirect the`/contact` page

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/137641079/7a9a8f06-e951-466c-9464-a1cc62b89af4)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by mohit-bhandari45** [comment]
its becaouse they have made contact and about page in one page itself

**Comment by Varsani2520** [comment]
If you assigned me i do the perfect footer link

**Comment by Yash636261** [comment]
issue is already resolved.
