### ISSUE TITLE
[Feat]: adding icons in navbar

### ISSUE THREAD

**Issue by dhairyagothi** [TechNodes2-0/ElectiveHub#276]
### Is your feature request related to a problem? Please describe.

i can add icons in navbar items home login register 
please assign the issue to me under gssoc 

### Describe the solution you'd like.

adding icons to home login register

### Show us the magic with screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/142989448/0a7e8d0e-bf20-40b9-bd56-8568e97f3e50)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
issue exists.
