### ISSUE TITLE
Goto homepage button redirects on login page

### ISSUE THREAD

**Issue by Sunny-unik** [TechNodes2-0/ElectiveHub#28]
### Description

When a user is not logged in and user clicks on the getting started button then the user is redirected to the 404 page where a goto homepage button is visible when the user clicks on that button user is redirected to the login screen which is inappropriate for the user.

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/65410458/5181b060-84d6-4279-a7f3-3b1dce1cb904)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by adityakhattri21** [comment]
I would like to work on this issue

**Comment by Nishitbaria** [comment]
Hey @Sunny-unik Thank you for your contribution ✨
