### ISSUE TITLE
Add dynamic year code in footer

### ISSUE THREAD

**Issue by arpit4521** [TechNodes2-0/ElectiveHub#280]
![Screenshot 2024-06-11 220316](https://github.com/TechNodes2-0/ElectiveHub/assets/127679958/1fdf8787-98cb-4b08-b8db-24f9ff2bc24b)

@Yash636261 please assign me this under gssoc and apt level label

**Comment by Yash636261** [comment]
assigning to you @arpit4521, you can start working on it.
