### ISSUE TITLE
Fix for Tablet size 768 px

### ISSUE THREAD

**Issue by Utsavladia** [TechNodes2-0/ElectiveHub#281]
### Is your feature request related to a problem? Please describe.

The website is not responsive for the tablet size it should be fixed to enhance the user experience on all the devices size.

### Describe the solution you'd like.

I would fix the overlap objects and make it breakdown on proper sizes

### Show us the magic with screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/124615886/f6d14c62-3144-4784-b9a6-d9a4ec5fab47)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
assigning to you @Utsavladia, you can start working on it.

**Comment by Utsavladia** [comment]
@Yash636261  
Sure
