### ISSUE TITLE
Adding Preloader in website 

### ISSUE THREAD

**Issue by dhairyagothi** [TechNodes2-0/ElectiveHub#282]
### Is your feature request related to a problem? Please describe.

I can add a preloader in website please assign this issue to me under gssoc 

### Describe the solution you'd like.

Adding a preloader to website 

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
assigning to you @dhairyagothi, you can start working on it.
