### ISSUE TITLE
Fix admin page left side nav-links styles

### ISSUE THREAD

**Issue by Sunny-unik** [TechNodes2-0/ElectiveHub#34]
### Description

Admin page left-side side nav links should have active class styles. 

### Screenshots

![admin page screenshot](https://github.com/TechNodes2-0/ElectiveHub/assets/65410458/f1a2d653-7d3f-4ce3-8dab-780e6dd308d5)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Yash636261** [comment]
@Sunny-unik you can start working on it.

**Comment by gkprasanth** [comment]
@Yash636261 Is this issue still open?

**Comment by Yash636261** [comment]
hey @gkprasanth ! , it is currently assigned to @Sunny-unik. you can have look to other open issues or find you own.
