### ISSUE TITLE
Redesign the login and sign up section.

### ISSUE THREAD

**Issue by Yash636261** [TechNodes2-0/ElectiveHub#36]
### Description

current design looks outdated make it look more morder yet simple.

### Screenshots

current design:
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/98970491/994e1c07-3c10-4468-9a62-a57d7d91fd79)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue. (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by hamzailyas237** [comment]
I would like to work on it. Assign me

**Comment by Yash636261** [comment]
Okay! @hamzailyas237 I'm assigning it to you. you can start working on it.

**Comment by hamzailyas237** [comment]
> Okay! @hamzailyas237 I'm assigning it to you. you can start working on it.

Done @Yash636261

**Comment by vyb2014962** [comment]
I would like to work on it. Assign me

**Comment by Yash636261** [comment]
Hey @vyb2014962 issue is already solved and closed. You can have a look to other issues or open one !!
