### ISSUE TITLE
[Feat]: stats incrment from 0 to current 

### ISSUE THREAD

**Issue by AKACHI-4** [TechNodes2-0/ElectiveHub#37]
### Is your feature request related to a problem? Please describe.

Homepage should be more effective and friendly what if all the stats start increment from zero to current count. 

### Describe the solution you'd like.

i would like to add small contribution so all the stats starts incrementing from zero to current count in same time.

### Show us the magic with screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/99159580/c631df2e-0d67-4b9f-9103-ce5391e090ed)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
@AKACHI-4 you can start working on it. also, currently this data is static try if you can make it dynamic.

**Comment by AKACHI-4** [comment]
Okay yah sure..

**Comment by AKACHI-4** [comment]
Hey, we're making it dynamic, so we have four key elements:

- Total Students: This refers to the total number of signed-up students, right?
- Subject: confused kindly explain ?
- Avg. Click Rate: I'll need to check if we can obtain this in real-time, but what's your view on it?
- Page Views: This represents the total number of visitors up to this point.

**Comment by AKACHI-4** [comment]
hey @Yash636261 i think the most of the site data is static and not real time...

**Comment by Yash636261** [comment]
> hey @Yash636261 i think the most of the site data is static and not real time... 
> 

Okay, leave it as it is. Just add that incrementing effect.

**Comment by AKACHI-4** [comment]
okay @Yash636261
