### ISSUE TITLE
Create User Profile Section✨

### ISSUE THREAD

**Issue by Nishitbaria** [TechNodes2-0/ElectiveHub#40]
Issue:
We want to create a User Profile section in our web application to enhance user experience and provide essential information about each user. This section will display the user's role, name, and their profile photo.

Proposed Solution:

**User Profile Section:**

- Implement a dedicated User Profile section within the user account dashboard.
- Display the user's role (e.g., "Admin," "Teacher," "Student," etc.) to indicate their permissions and responsibilities.
- Show the user's name, making it more personal and identifiable.
- Allow users to upload and display a profile photo/avatar.

**Comment by VishalGaurav01** [comment]
Can create a fully functional User Profile section on your Website and add the rest of the provided details on the page. 
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/97465452/8b42b230-8736-4992-a357-babfeb7ad3c9)
Assignee: Please Assign this issue to me.

**Comment by Vivek-yadav01** [comment]
i m frontend developer with good hand in mern tech stack ,could you assign this to me?

**Comment by piyush-gangrade** [comment]
I want to work on this feature, could you assign this to me ?

**Comment by Adi-gitX** [comment]
Problem Statement:
Our web application lacks a dedicated User Profile section, which diminishes user experience and restricts access to vital user information.

Proposed Solution:
User Profile Section: Develop a dedicated section within the user account dashboard exclusively for user profiles, enhancing accessibility to essential user details.
Display User Role: Prominently display the user's role (e.g., "Admin," "Teacher," "Student") to signify their permissions and responsibilities, aiding in user identification and understanding.
Show User's Name: Personalize the user experience by prominently displaying the user's name, fostering a sense of connection and familiarity with the application.
Profile Photo/Avatar: Introduce functionality for users to upload and showcase a profile photo or avatar, enriching personalization and facilitating easier recognition among users.

i have reviewed the problem statement and understand how to solve it. Please assign me the issue.

**Comment by VishalGaurav01** [comment]
I have completed your previous task and have the optimum solution for the User Profile Section.
Assignee: Kindly assign this issue to me.

**Comment by Nishitbaria** [comment]
> I have completed your previous task and have the optimum solution for the User Profile Section. Assignee: Kidly assign this issue to me.

 you can start working on this issue @VishalGaurav01 
happy hacking ✨

**Comment by Nishitbaria** [comment]
> i m frontend developer with good hand in mern tech stack ,could you assign this to me?
> 

Hey can you checkout my other project for that : 

GitHub.com/Nishitbaria/opengrame

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!
