### ISSUE TITLE
Create Docker Containers for Our App⚡

### ISSUE THREAD

**Issue by Nishitbaria** [TechNodes2-0/ElectiveHub#41]
Issue:
We want to make it easier to run our application and ensure that it works consistently on different computers. To do this, we're going to create Docker containers for our app.

Proposed Solution:

1. Docker Containers:

- Docker containers are like little packages that contain everything our app needs to run.
- We'll create these containers to package our app and its dependencies together.
- This will make it simple for anyone to run our app, no matter where they are.

**Comment by sirish123** [comment]
I should  docker file and dockercompose file right?

**Comment by Nishitbaria** [comment]
yes @sirish123

**Comment by Orange-Tofu** [comment]
I would like to give this a try. Can you assign it to me?

**Comment by Nishitbaria** [comment]
Hey you can work on this issue @Orange-Tofu
