### ISSUE TITLE
buttons are not aligned for chatbot and go to top

### ISSUE THREAD

**Issue by Yash636261** [TechNodes2-0/ElectiveHub#43]
### Description

buttons in corners are not aligned

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/98970491/fbbc1cba-d21a-432a-9782-40f27ab25d5c)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue. (optional)

**Comment by SharmaDhruv2511** [comment]
Hi I want to contribute to this issue. Can you assign me?

**Comment by SharmaDhruv2511** [comment]
Solution by applying margin 12 from the right side make it align with the AI Chat bot button

**Comment by Yash636261** [comment]
you can start working on it @SharmaDhruv2511 . also trying to reduce the size of chatbot button so it looks appropriate to the go to top button.

**Comment by SharmaDhruv2511** [comment]
Where can i find the AI chat button style code I am unable to find it. Can you please help it? @Yash636261

**Comment by SharmaDhruv2511** [comment]
I guess the height and width of the button is coming from the API which is containing the default CSS So its not able to change. Or is there anything which i am missing out to solve it you can guide me @Yash636261

**Comment by Yash636261** [comment]
You can align go to the top button then.
It would work @SharmaDhruv2511 .

**Comment by SharmaDhruv2511** [comment]
I have already align it as mention in above screen shot

**Comment by SharmaDhruv2511** [comment]
The height and width of Alan chat button is 64px and its not changeable. So I  change the height and width of Go to top button to 64px and align it to the bottom of alan chat button and it looks like this

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/102755411/83e4bb6e-4d2a-4c32-8dbe-9e7f95252201)

if it looks good  I can raise a PR @Yash636261. Please Check it out

**Comment by Yash636261** [comment]
> The height and width of Alan chat button is 64px and its not changeable. So I change the height and width of Go to top button to 64px and align it to the bottom of alan chat button and it looks like this
> 
> ![image](https://user-images.githubusercontent.com/102755411/278864001-83e4bb6e-4d2a-4c32-8dbe-9e7f95252201.png)
> 
> if it looks good I can raise a PR @Yash636261. Please Check it out

yes, you can go for it.

**Comment by SharmaDhruv2511** [comment]
I forgot to address the issue can you please add in to this repo otherwise my contribution will not count in hacktoberfest @Yash636261

**Comment by SharmaDhruv2511** [comment]
is this contribution count for Hacktoberfest 2023 @Yash636261 ??

**Comment by Yash636261** [comment]
> is this contribution count for Hacktoberfest 2023 @Yash636261 ??

yes, it will. don't worry about that. if you need any further help or assistant fell free to ask. : )
