### ISSUE TITLE
Improve visibility of chart font color in dark mode

### ISSUE THREAD

**Issue by JayeshYadav99** [TechNodes2-0/ElectiveHub#44]
### Description

**Issue Description:**

Currently, the font color of the charts becomes less visible when the application is in dark mode. This makes it challenging for users to read the data presented on the charts, consequently affecting the user experience. 

**Expected Behavior:**

The font color of the charts should be adjusted to ensure optimal visibility even in dark mode. This would enhance the user experience by allowing users to easily read and interpret the data displayed on the charts irrespective of the mode the application is in.

**Steps to Reproduce:**

1. Enable dark mode in the application.
2. Navigate to any section where charts are displayed.
3. Observe the font color of the text on the charts.

**Current Behavior:**

The font color of the text on the charts becomes less visible or almost indistinguishable in dark mode, making it difficult for users to read the data.

**Proposed Solution:**

Adjust the font color of the charts to a more contrasting and visible color when the application is in dark mode. This will ensure that the data presented on the charts remains easily readable regardless of the mode the application is in.

**Additional Information:**

- Operating System: [Insert operating system name and version]
- Browser: [Insert browser name and version]
- Screen Resolution: [Insert screen resolution if applicable]
- Application Version: [Insert application version if applicable]

Please feel free to reach out for any further clarification or details needed.

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/107855172/a7a36985-3d85-4246-becf-0a56cea86887)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by JayeshYadav99** [comment]
please assign me this issue

**Comment by VinayakVispute** [comment]
@JayeshYadav99 You can Start Working 🤘🤘 Happy Hacking
