### ISSUE TITLE
Problem with the floating button.

### ISSUE THREAD

**Issue by ivanosquis10** [TechNodes2-0/ElectiveHub#5]
By touching the button that is floating in the middle of the screen, a blue one. When you click on it, it opens a kind of chat and does not let you close it in any way. In fact, when refreshing the page, it is still displayed.

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/83567373/0cac894b-3d5b-40d9-acfa-47955afa2862)

**Comment by Nishitbaria** [comment]
You can start to work on this issue: @ivanosquis10 Happy hacking ⚡

**Comment by gkprasanth** [comment]
@Nishitbaria Can I work on this issue?

**Comment by ivanosquis10** [comment]
> Hey @ivanosquis10 are you working on this issue?? 

Hey, sorry. I'll do the PR in a few hours.

**Comment by ivanosquis10** [comment]
@gkprasanth if you want to do it yourself, I won't be able to code for a few days...sorry :/

**Comment by gkprasanth** [comment]
> @gkprasanth if you want to do it yourself, I won't be able to code for a few days...sorry :/

Okay @ivanosquis10 I will work on it. Thank you.

**Comment by gkprasanth** [comment]
@Nishitbaria Can you assign me the issue?

**Comment by Yash636261** [comment]
> @Nishitbaria Can you assign me the issue?

I'm assigning it to you, you can start working on it !

**Comment by Yash636261** [comment]
@gkprasanth any progress ?
