### ISSUE TITLE
Improving the style of features section.

### ISSUE THREAD

**Issue by bilalshaikh292** [TechNodes2-0/ElectiveHub#58]
### Is your feature request related to a problem? Please describe.

the feature page should have better CSS and some CSS features.
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/110531971/3065a0ec-d639-4fbb-991a-7acafb247485)

### Describe the solution you'd like.

I would like to change the text color of the 'features' word give it some underline offset and give a box shadow to the div below it.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
I'm assigning this to you @bilalshaikh292, can you share design first that you gonna implement?

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by SumitKumar-17** [comment]
@Yash636261 I want to work on this issue. Can you assign this issue to me under GSSoc'24?

**Comment by bilalshaikh292** [comment]
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/110531971/b9caaa4c-6972-4f97-b2bb-01ae63df8977)
