### ISSUE TITLE
 Improve User Experience on Learning Path Pages (Timeline and Tree)

### ISSUE THREAD

**Issue by RashidSiddiqui2004** [TechNodes2-0/ElectiveHub#62]
### Description

**_Initial Load Position and Levels in Learning Path Tree Page:_**
The central node of the learning path tree is initially positioned at the top left of the screen, hindering visibility and understanding for users.

Increasing the number of initial levels to 2 can provide users with a clearer overview and context of the learning path.

**_Image Collision with Timelines in Time Learning Path Page:_**
On the Time learning path page, the image collides with timelines at the bottom, affecting layout and readability.

### Screenshots

![issue1](https://github.com/TechNodes2-0/ElectiveHub/assets/124426004/16ae5c68-327f-44f0-8c40-77fbecc890c8)

![issue2 (2)](https://github.com/TechNodes2-0/ElectiveHub/assets/124426004/c3981ab6-744b-4836-9e9a-fb55d28d3aba)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by himanshugoyal77** [comment]
I have started to work on it

**Comment by RashidSiddiqui2004** [comment]
@himanshugoyal77 I have already requested for the task assignment to me.

**Comment by Yash636261** [comment]
Appreciating your efforts @himanshugoyal77, but @RashidSiddiqui2004 created issue and he was ready to work on it. so, as per contribution guidelines he will be prioritized to assigning this to him.
