### ISSUE TITLE
[Feat]: Removing Social Links

### ISSUE THREAD

**Issue by Waqas-1114** [TechNodes2-0/ElectiveHub#64]
### Is your feature request related to a problem? Please describe.

The social link on "ElectiveHub" is currently non-functional, failing to redirect users to the home page upon clicking.
I'm looking to contribute a fix to ensure it is working properly for users to redirect to social of "ElectiveHub".
I request you to assign me this issue under GSSOC'24.

### Describe the solution you'd like.

I'll add all socials link of "ElectiveHub" in the website.

### Additional context.

I can also add some hover effect.

### Show us the magic with screenshots

Before clicking
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/146182663/77e5a427-e0a2-41f1-a1bf-0a7dab70c5e4)
After Clicking, Nothing Happen
![Socials](https://github.com/TechNodes2-0/ElectiveHub/assets/146182663/3d22f70f-cec9-474e-afaa-1e16449fb30c)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Waqas-1114** [comment]
I want to work on the issue, Please @Yash636261  to assign it to me.

**Comment by SumitKumar-17** [comment]
@hardy07 I want to work on this issue. Can you assign this issue to me under GSSoc'24?

**Comment by Yash636261** [comment]
Hey @Waqas-1114, we don't have any accounts for social media for elective Hub right now. so, you can remove that section as of now.

**Comment by AMISH-KHAN** [comment]
@Yash636261 I would like to work on this. Please assign this issue to me

**Comment by Waqas-1114** [comment]
I removed the socials section as i have asked to do. Also pulled request . Please check.
