### ISSUE TITLE
[Feat]: Adding the GSAP(JS Library) Animations to the website

### ISSUE THREAD

**Issue by suraj-9849** [TechNodes2-0/ElectiveHub#68]
### Is your feature request related to a problem? Please describe.

For this electionHub website I felt to add some best animations which can help the user feel good 

### Describe the solution you'd like.

So I will be using the GSAP(Javascript animation library) where I will be adding the best animations to this website 

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by suraj-9849** [comment]
I would like to work on this. So can you please assign this to me!

**Comment by Yash636261** [comment]
Liked your idea, but I need more clarification about what changes or animation you going to implement.

**Comment by suraj-9849** [comment]
Yeah I will be adding the sliding animations on the Navbar like when the server starts or when the page reloads the Navbar elements comes from the top and place in the current place.and add the hero session like it scales and comes out such type of animations I will be adding these are called as microInteractions which can enhance the website interface and give the best experience for the website

**Comment by Yash636261** [comment]
okay, you can start working on it.

**Comment by suraj-9849** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7180274007328321536/ this is the project which was made by team in hackathon

**Comment by suraj-9849** [comment]
I will be making like this

**Comment by Yash636261** [comment]
> I will be making like this

No Problem, take your time.

**Comment by suraj-9849** [comment]
https://github.com/TechNodes2-0/ElectiveHub/assets/146669517/bf506dbd-1511-480c-968f-29612a599d68


https://github.com/TechNodes2-0/ElectiveHub/assets/146669517/b15a8ce5-9b11-4d79-a42b-ce8fbfa3f59e

is this ok sir . Or should I make more changes I included the Locomotive JS u might not see in the video the smoothness when I push it u can experience it

**Comment by Yash636261** [comment]
> ElectiveHub.-.Brave.2024-05-11.17-14-13.mp4 
>  ElectiveHub.-.Brave.2024-05-11.17-15-00.mp4 
> is this ok @Yash636261 . Or should I make more changes I included the Locomotive JS u might not see in the video the smoothness when I push it u can experience it

looks cool just make few changes
- make that navbar elements load faster and other animations too (no one likes to wait that much)
- on login page keep that illustration image static (bounce effect attracts too much attention which should be on form)

**Comment by suraj-9849** [comment]
Yeah I will make those changes

**Comment by suraj-9849** [comment]
I made the necessary changes @Yash636261 . and create a PR

**Comment by suraj-9849** [comment]
Thank you for assigning this issue to me @Yash636261
