### ISSUE TITLE
Add Back-to-top button

### ISSUE THREAD

**Issue by Yash636261** [TechNodes2-0/ElectiveHub#7]
add back-to-top button on all pages, as user scrolls down then it gets annoying to scroll to top.

**Comment by SumitMangrati** [comment]
hey can you assign me this ill work on it

**Comment by Yash636261** [comment]
assigned to you.

**Comment by SumitMangrati** [comment]
could you please add the Hacktoberfest tag as well want to add this as one of my PR

**Comment by Nishitbaria** [comment]
Hey @SumitMangrati  any update ??

**Comment by SumitMangrati** [comment]
sorry have been busy with college curriculum, you can assign the issue to someone else, really sorry

**Comment by hardy07** [comment]
if this issue isnt assigned to anyone, can i get assigned?

**Comment by Yash636261** [comment]
hii @hardy07, you can work on it.
