### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [TechNodes2-0/ElectiveHub#70]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behavior, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Kindly assign me this issue.

**Comment by dhruv8433** [comment]
@TechNodees2-0 i would like to work on this issue and creating code of conduct file please assign it to me

**Comment by Yash636261** [comment]
@suhanipaliwal assigning this to you. you can start working on it.
