### ISSUE TITLE
 Multiple Users Able to Register with the Same Username[Feat]: 

### ISSUE THREAD

**Issue by divyanshahlawat** [TechNodes2-0/ElectiveHub#71]
I have identified a potential security vulnerability within our application's user registration system. It appears that the system allows multiple users to register with the same username, which poses significant risks to data integrity and user account security.

### Describe the solution you'd like.

Implement server-side validation to enforce uniqueness constraints on usernames during the registration process.
Enhance error handling to provide clear feedback to users when attempting to register with a username that is already in use.
Perform thorough testing to ensure that the fix is effective and does not introduce any regressions.

### Additional context.

This security vulnerability poses significant risks to our application's data integrity and user account security. I urge the development team to prioritize the implementation of a fix to enforce uniqueness constraints on usernames and mitigate the associated risks.

@TechNodes2-0  please assign this issue to me under GSSOC

**Comment by amrit1004** [comment]
I would want to contribute to it pls assign me this issue under gssoc

**Comment by Yash636261** [comment]
@divyanshahlawat you can start working on it, assigning to you.

Hey @amrit1004 I appreciate your efforts to resolve issue but, I can't assign this to you cause one who creates issue is prioritized first. from next please get issue assigned to you before working on it.

Happy Hacking.

**Comment by divyanshahlawat** [comment]
@Yash636261 I am pleased to inform you that the issue regarding [brief description of the issue] has been successfully resolved and my PR is merged with main project.
