### ISSUE TITLE
Social Media Links are not working

### ISSUE THREAD

**Issue by Anshika040** [TechNodes2-0/ElectiveHub#73]
### Description

Socail Media links in footer section at last are not working . Please assign this issue to me

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Madhuri36** [comment]
I would like to work on this. Please assign this to me under GSSoC'24.

**Comment by Yash636261** [comment]
Hey @Anshika040, this issue is already mentioned, and it is already assigned to someone so you can look for other issues.

Regards
