### ISSUE TITLE
Links of about, privacy policy, licensing, contact are not workinh

### ISSUE THREAD

**Issue by Anshika040** [TechNodes2-0/ElectiveHub#74]
### Description

Links of about, privacy policy, licensing, contact are not working are not redirecting to the desired webpages.

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/140148419/f95f0dac-2f94-4488-b8fd-f568779c9cdd)

### Additional information

Links must redirect to the desired information webpage

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
I'm assigning this to you @Anshika040 , you can start working on it.

**Comment by Anshika040** [comment]
Issue no:- #74
Links of about, privacy policy, licensing, contact are now working properly.
Issue solved
