### ISSUE TITLE
fix: Chat Dialog not working properly

### ISSUE THREAD

**Issue by DeadAnjali** [TechNodes2-0/ElectiveHub#79]
### Description

**To Produce issue**

1. Click on any link that takes to login page
2. Click on the message circle icon

**Exact Issue**
The top of the chat dialog is not visible on all screen sizes

### Screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/122856861/4989d009-5ae2-4b78-85b4-1cca6f256b33)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
assigning to you @DeadAnjali you can start working on it.

**Comment by Manaswini123456** [comment]
@Yash636261 kindly assign me this issue

**Comment by Yash636261** [comment]
> @Yash636261 kindly assign me this issue

Hey @Manaswini123456 , I can't assign this to you as this one is already assing this to you. you can look for other open issues or create your own!

**Comment by Manaswini123456** [comment]
@Yash636261 ok will look into other issues.

**Comment by DeadAnjali** [comment]
Thank you, I am working on it.
