### ISSUE TITLE
Enhancing signup feature

### ISSUE THREAD

**Issue by Nupur19nj** [TechNodes2-0/ElectiveHub#8]
Hey!
Currently there is no check for password length and type of password also for email in signup. So i want to resolve this issue, can you please assign this to me under Hacktoberfest-accepted!
Thank you!

**Comment by Yash636261** [comment]
You can start to work on this issue: @Nupur19nj Happy hacking ⚡

**Comment by JayeshYadav99** [comment]
@Nupur19nj ,please apply validation for all fields  ,also show custom error message

**Comment by Nupur19nj** [comment]
okay!

**Comment by Parthasarathip123** [comment]
can you assign me this issue @Nupur19nj

**Comment by Nupur19nj** [comment]
Email validations:
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/114866308/3dd7179e-af96-40c7-872f-a8cbefa99615)
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/114866308/19b25c27-1733-4487-bfac-5957619efa7a)

Password validations:
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/114866308/c830e668-6e21-4c3e-85ac-cfecbcf1f70c)

**Comment by Nupur19nj** [comment]
Completed the task and initiated the PR kindly look into that and merge!
