### ISSUE TITLE
Responsive fix On User Dashboard

### ISSUE THREAD

**Issue by geoffgeorgein** [TechNodes2-0/ElectiveHub#82]
### Description

User dashboard is not responsive
![dash00332](https://github.com/TechNodes2-0/ElectiveHub/assets/52931060/7392e042-4c64-4c84-a64d-bea411ffa363)

assign me and I will work on this.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
go for it, I'm assigning this to you.

**Comment by geoffgeorgein** [comment]
Hi,
I need values of  the following env variables MONGO_URL PORT TOKEN_KEY
