### ISSUE TITLE
[Feat]: Improve the Stats section

### ISSUE THREAD

**Issue by mahekkg** [TechNodes2-0/ElectiveHub#83]
### Is your feature request related to a problem? Please describe.

Hello Team,

Upon reviewing our website, I've identified an issue with the UI in the current stats section, which appears to conflict with the overall design aesthetics. Drawing from my experience in contributing to open-source projects, I'm confident in addressing this issue effectively.

Looking forward to discussing and implementing solutions together!
Please assign this issue to me under GSSOC'24

### Describe the solution you'd like.

We should focus on maintaining consistency in typography, color schemes, and layout to create a cohesive visual experience for users.

### Show us the magic with screenshots

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/85817366/15898e21-e360-4ef3-b857-43d3b97522b9)

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Loved your idea you can start working on it.

just share me any reference of design or improvement you going to do.

**Comment by mahekkg** [comment]
@Yash636261 , thanks for assigning the issue 

PR - https://github.com/TechNodes2-0/ElectiveHub/pull/98
