### ISSUE TITLE
Improve the login page responsiveness 

### ISSUE THREAD

**Issue by GOURAVSINGH19** [TechNodes2-0/ElectiveHub#85]
### Description

![Screenshot 2024-05-11 211218](https://github.com/TechNodes2-0/ElectiveHub/assets/120244528/159fa238-a8b4-482a-8682-ff6121aea1c8)
 Login page is not responsive

second issue is when we go on login or sign up background is not update
![Screenshot 2024-05-11 211227](https://github.com/TechNodes2-0/ElectiveHub/assets/120244528/ec008883-417e-4cb0-96e1-dc7652d272e2)

### Additional information

If you think  it is valuable issue then assign me.

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue. (optional)

**Comment by GOURAVSINGH19** [comment]
@Yash636261

**Comment by Yash636261** [comment]
you can start working on it @GOURAVSINGH19 .

**Comment by sohan-gupthak** [comment]
Hello @Yash636261 i have found that in mobile view the icons having more space in between and also icons are merging with the lower copilot icon. Please assign me this issue under GSS0C'24
![Screenshot (59)](https://github.com/TechNodes2-0/ElectiveHub/assets/122393891/2a6ab39e-70f3-49e1-801b-749d63020049)
LinkedIn - https://www.linkedin.com/in/sohan-guptha/
Mail - sohan.gupthak@gmail.com
