### ISSUE TITLE
[BUG] Already Existing User Alert/Toast

### ISSUE THREAD

**Issue by aryansharma220** [TechNodes2-0/ElectiveHub#87]
### Description

When I tried to sign in with an already created user id /email, I don't get any warning/ alert. It just console logs the alert in the console.

### Screenshots

https://github.com/TechNodes2-0/ElectiveHub/assets/133234867/d6121e05-f2d7-4789-b023-1fd01ab87f69

### Additional information

I would like to add an alert/ toast to show the alert to the user.
@Yash636261 Please assign it to me under gssoc 24.

### What browser are you seeing the problem on?

Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by abhiperfect** [comment]
Subject: Request to Fix Alert/Toast Issue for Existing Users

Hi Mentor ,

Could you assign me the task to resolve the alert/toast issue for existing users? I believe I can address it effectively.

Best regards,
Abhishek

**Comment by Yash636261** [comment]
assigning this to you @aryansharma220 , you can start working on it.
