### ISSUE TITLE
Improving the newsletter part

### ISSUE THREAD

**Issue by tanu-agarwal0101** [TechNodes2-0/ElectiveHub#89]
### Issue Description

The email id and the placeholder are written on each other. I would like to fix this.
Please assign this to me under gssoc'24

### Screenshots or Examples (if applicable)

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/162132053/65cd54c6-f0f1-4acb-bc46-2b9a0582bb7d)

### Checklist

- [X] I have checked the existing [issues](https://github.com/TechNodes2-0/ElectiveHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by abhiperfect** [comment]
Subject: Enhancing the Newsletter Section

Hi sir ,

I hope this message finds you well. I've been thinking about ways to improve our newsletter section, aiming to enhance engagement and deliver more value to our subscribers.

I'm keen to collaborate on this project and explore various strategies to elevate our newsletter content and delivery.


Best regards,
Abhishek

**Comment by Yash636261** [comment]
Assigning to you @tanu-agarwal0101 ,you can start working on it.

**Comment by tanu-agarwal0101** [comment]
> Assigning to you @tanu-agarwal0101 ,you can start working on it.

Ok thank you sir

**Comment by tanu-agarwal0101** [comment]
@Yash636261 
Please check PR#111
