### ISSUE TITLE
✨ Enhancing Website Loading Experience with Loading Animation 🚀

### ISSUE THREAD

**Issue by VinayakVispute** [TechNodes2-0/ElectiveHub#9]
# Issue Description

### Problem: 🚀
The website currently displays a static "loading...." text during the loading phase, which isn't visually engaging. This issue aims to replace it with a loading animation to enhance the user experience.

### Background: 🌐
Users expect a visual loading animation when accessing our website.

## Video Reference:
[Watch Video](https://github.com/TechNodes2-0/ElectiveHub/assets/93467074/1e1609d1-20b6-4ba8-af24-ab3485769fbc)

**Comment by adityakhattri21** [comment]
I am interested to work on this issue

**Comment by VinayakVispute** [comment]
You can start to work on this issue: @adityakhattri21  Happy hacking ⚡

**Comment by VinayakVispute** [comment]
@adityakhattri21, you can make use of websites like [CssLoader](https://cssloaders.github.io/) to incorporate loading animations into your web design. 💻✨

**Comment by adityakhattri21** [comment]
Sure I will look into this

**Comment by adityakhattri21** [comment]
PR linked with the issue #12

**Comment by adityakhattri21** [comment]
Can you close this issue as you have merged the PR
