### ISSUE TITLE
No option to signup with google

### ISSUE THREAD

**Issue by tanu-agarwal0101** [TechNodes2-0/ElectiveHub#90]
### Issue Description

I would like to add an option to signup with google on the sign up page.
Please assign this to me under GSSOC'24

### Screenshots or Examples (if applicable)

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/162132053/f6c0fec0-8899-42cb-85ef-f83a9972ffca)

### Checklist

- [X] I have checked the existing [issues](https://github.com/TechNodes2-0/ElectiveHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Yash636261** [comment]
Hey @tanu-agarwal0101 , we are not planning goole sign up as there is no need of it as of now. so, I'm closing this issue.
