### ISSUE TITLE
Navbar: Home in blue even when it is not active

### ISSUE THREAD

**Issue by tanu-agarwal0101** [TechNodes2-0/ElectiveHub#92]
### Issue Description

In Navbar Home is in blue even when it is not active. I would like to work on this under gssoc'24

### Screenshots or Examples (if applicable)

![image](https://github.com/TechNodes2-0/ElectiveHub/assets/162132053/cfbfb467-7743-4839-86c6-417f20caaf8b)

### Checklist

- [X] I have checked the existing [issues](https://github.com/TechNodes2-0/ElectiveHub/issues?q=is%3Aissue+)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)

**Comment by Yash636261** [comment]
That's how it's designed to work, although I can assign you as I want that home link to be in light blue color.

**Comment by tanu-agarwal0101** [comment]
I have made a pr, please check it out @Yash636261

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
