### ISSUE TITLE
[Feat]: I want to add smooth scrolling while navigating between sections through the navbar and footer.

### ISSUE THREAD

**Issue by abhiperfect** [TechNodes2-0/ElectiveHub#93]
### Is your feature request related to a problem? Please describe.

The feature request is related to enhancing user experience by implementing smooth scrolling when navigating between sections using the navbar and footer.

### Describe the solution you'd like.

The solution I'd like involves adding smooth scrolling functionality to our website so that when users click on links in the navbar or footer to navigate between sections, the page smoothly scrolls to the target section instead of instantly jumping to it. This would provide a more seamless and visually appealing browsing experience for our users.

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
this feature is already added to webpage recently. closing this now.
