### ISSUE TITLE
[Feat]:  Add Some Links to Connect students together 

### ISSUE THREAD

**Issue by aasthakourav20** [TechNodes2-0/ElectiveHub#94]
### Is your feature request related to a problem? Please describe.

No, it's not a problem but a user friendly  feature we can add  like we can provide links to  whatsapp and telegram channels where
all the connected students can discuss together .

### Describe the solution you'd like.

I would to add one section , which includes link to  whatsapp and telegram channels , and would like to add some title to the links 

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
Currently the WhatsApp or telegram channels are not planned for this project. So I'm closing this issue for now.

If there will be requirement of such feature in future will reopen this.
