### ISSUE TITLE
[Feat]: Created a card layout for login and signup

### ISSUE THREAD

**Issue by Sailesh3000** [TechNodes2-0/ElectiveHub#96]
### Is your feature request related to a problem? Please describe.

I want to create a card like layout for login and signup so that it is more interactive for the users

### Describe the solution you'd like.

I want to create a card like layout for login and signup so that it is more interactive for the users I am a GGSOC'24 Contributor so please assign me this issue and make a label for this issue

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment]
can you show me reference design?

**Comment by Sailesh3000** [comment]
![image](https://github.com/TechNodes2-0/ElectiveHub/assets/126142666/d6ee145d-404e-46d7-8ed9-097236c43702)
is this design ok I can update it if you want . Thank You

**Comment by Yash636261** [comment]
looks fine to me, go for it. just use border, reduce shadow size and use dark color in gray shade.

assigning to you.
