### ISSUE TITLE
[Feat]: Add some style to user welcome notes

### ISSUE THREAD

**Issue by safal45** [TechNodes2-0/ElectiveHub#97]
### Is your feature request related to a problem? Please describe.

![Screenshot from 2024-05-12 10-50-44](https://github.com/TechNodes2-0/ElectiveHub/assets/130926002/da67504f-c464-466e-a65a-eb7de6917b7a)

### Describe the solution you'd like.
I want to give it some style so that it looks good to the user

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by safal45** [comment]
please assign me this task under GSSOC'24 so that I may work over it
@Yash636261

**Comment by safal45** [comment]
is someone already working on it ??
@Yash636261

**Comment by Yash636261** [comment]
you can start working on it @safal45 . assigning to you.

**Comment by sohan-gupthak** [comment]
I would like to work on this issue. please assign me this issue under GSSoC'24
LinkedIn - https://www.linkedin.com/in/sohan-guptha/

**Comment by safal45** [comment]
@Yash636261
Could you please review Pull Request #131 and let me know if any updates are needed?
