### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [TechNodes2-0/ElectiveHub#99]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by Anumallasarayu123** [comment]
I can fix the issue I can create good Contributing.md file in the repository
Can u please assign the issue under GSSOC 2024.

**Comment by Yash636261** [comment]
> The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.
> 
> Could you please assign this issue to me under GSSOC 24.

assigning this to you @suhanipaliwal ,you can start working on it.
